name: CI Pipeline

# Define the event trigger
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Updated to the latest version

    - name: Set up Node.js 20
      uses: actions/setup-node@v4  # Updated to v4 to ensure Node.js 20 is used
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm test
